#!/bin/sh

#
# Gradle start up script for POSIX generated by the Gradle wrapper plugin.
#
# IMPORTANT: This file's gradle-wrapper.jar counterpart is intentionally NOT
# included in this generated project (binary jars cannot be produced by this
# generator). Before first use, run `gradle wrapper` with any locally
# installed Gradle 8.x to populate gradle/wrapper/gradle-wrapper.jar, or
# download it directly from:
#   https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar
# and place it at gradle/wrapper/gradle-wrapper.jar. See README.md.
#

APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)

JAVA_EXE="java"
if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVA_EXE="$JAVA_HOME/bin/java"
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

exec "$JAVA_EXE" -Dorg.gradle.appname="$(basename "$0")" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
