package MineGamer.civilizationai.domain.road;

import MineGamer.civilizationai.domain.CivilizationManager;
import MineGamer.civilizationai.domain.construction.BlockPlacement;
import MineGamer.civilizationai.domain.construction.ConstructionJob;
import net.minecraft.core.GlobalPos;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.List;
import java.util.UUID;

/**
 * A road under construction: a queue of ground-following
 * {@link BlockPlacement}s generated by
 * {@link MineGamer.civilizationai.world.RoadPathGenerator}. Unlike buildings,
 * roads have no resource cost in this phase (see the Javadoc on
 * {@link MineGamer.civilizationai.ai.RoadPlanner} for why that's a deliberate
 * scope cut, not an oversight) — completion only needs to register the
 * resulting {@link RoadSegment}.
 */
public final class RoadConstructionSite implements ConstructionJob {

    private final UUID id;
    private final UUID civilizationId;
    private final GlobalPos start;
    private final GlobalPos end;
    private final Deque<BlockPlacement> queue;

    public RoadConstructionSite(UUID id, UUID civilizationId, GlobalPos start, GlobalPos end, List<BlockPlacement> plan) {
        this.id = id;
        this.civilizationId = civilizationId;
        this.start = start;
        this.end = end;
        this.queue = new ArrayDeque<>(plan);
    }

    /** Reconstruction used by the serializer — {@code remainingPlan} is whatever hadn't been placed yet. */
    public static RoadConstructionSite reconstruct(UUID id, UUID civilizationId, GlobalPos start, GlobalPos end,
                                                     List<BlockPlacement> remainingPlan) {
        return new RoadConstructionSite(id, civilizationId, start, end, remainingPlan);
    }

    @Override
    public UUID getId() {
        return id;
    }

    @Override
    public UUID getCivilizationId() {
        return civilizationId;
    }

    /** The start point doubles as the origin every placement's relative position is offset from. */
    @Override
    public GlobalPos getOrigin() {
        return start;
    }

    public GlobalPos getStart() {
        return start;
    }

    public GlobalPos getEnd() {
        return end;
    }

    public List<BlockPlacement> getRemainingPlan() {
        return List.copyOf(queue);
    }

    @Override
    public boolean isComplete() {
        return queue.isEmpty();
    }

    @Override
    public List<BlockPlacement> takeNextBatch(int maxCount) {
        List<BlockPlacement> batch = new ArrayList<>(Math.min(maxCount, queue.size()));
        for (int i = 0; i < maxCount && !queue.isEmpty(); i++) {
            batch.add(queue.pollFirst());
        }
        return batch;
    }

    @Override
    public void onComplete(CivilizationManager manager, long gameTime) {
        manager.registerRoadSegment(new RoadSegment(UUID.randomUUID(), civilizationId, start, end, gameTime));
    }
}
